FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /workspace/target/bank-simulator-1.0-SNAPSHOT.jar /app/bank-simulator.jar

RUN mkdir -p /app/data

EXPOSE 8080

CMD ["java", "-jar", "/app/bank-simulator.jar"]
